image:
  file: dev.docker
tasks:
- init: './hack/setup-workspace.mjs'
vscode:
  extensions:
  - streetsidesoftware.code-spell-checker
  - EditorConfig.EditorConfig
  - dbaeumer.vscode-eslint
  - FallenMax.mithril-emmet
